#!/bin/sh
sudo npm install --save react-router-dom
sudo npm install --save flexbox-react
sudo npm install styled-components
sudo npm install --save react-horizontal-scroll-container --force
sudo npm install --save @chakra-ui/react