#!/bin/sh
npm install --save react@^16.0.0
npm install --save react-dom@^16.0.0
npm install --save react-router-dom
npm install --save flexbox-react
npm install styled-components
npm install -S horizontal-scroll
npm install --save @chakra-ui/react
npm install --save react-toastify
npm install --save styled-components
npm install --save react-jwt